python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 04-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 06-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 07-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 08-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 09-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 11-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 14-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 15-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 16-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 20-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 23-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 27-Apr-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/Copy of B2C FG BPR REPORT DATED 02-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 03-May-22.xlsx" 
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 04-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 05-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 06-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 07-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 09-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 10-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 11-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 12-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 13-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 14-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 16-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 18-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/B2C FG BPR REPORT DATED 19-May-22.xlsx"
python starter.py --bpr "/content/drive/MyDrive/BPR Report/Copy of B2C FG BPR REPORT DATED 26-May-22.xlsx"

